# HW5: Feature Engineering Pipeline на PostgreSQL (Olist)

Дзеркало у **Google Colab** середовищі:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1aYgBVIl_qBttZxxm2vuGCwmZ5zep530H?usp=sharing)


**Мета:**
> відтворюваний customer-level feature store:
> * raw-шар
> * $\rightarrow$ typed-схема з constraints
> * $\rightarrow$ CTE-chain (8 named stages)
> * $\rightarrow$ recursive CTE (referral graph)
> * $\rightarrow$ Materialized View + `REFRESH CONCURRENTLY`
> * $\rightarrow$ порівняння вартості через `EXPLAIN (ANALYZE, BUFFERS)`
> * $\rightarrow$ Reflection.

**Джерело даних (відтворюване, без ручних кроків):**
1. `kagglehub.dataset_download("olistbr/brazilian-ecommerce")` $-$ основне джерело (Kaggle).
2. Якщо Kaggle недоступний (немає credentials / мережі) $-$ `git clone` публічного GitHub-дзеркала `spdrio/Brazilian-E-Commerce-Public-Dataset-by-Olist` у `/tmp/olist_mirror`.

Notebook розрахований на **Runtime → Restart & Run All** у Google Colab.

## 1. Setup і typed-схема Olist

### 1.1. Запуск PostgreSQL і перевірка підключення

In [2]:
# PostgreSQL in Colab
!apt-get -qq update > /dev/null
!apt-get -qq install -y postgresql > /dev/null
!service postgresql start
# password for the user
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

!pip install -q sqlalchemy psycopg2-binary pandas ipython-sql
!pip install -q kagglehub

import os
import glob
import subprocess
import pandas as pd
from sqlalchemy import (
    create_engine,
    text
)
import kagglehub

engine = create_engine(
  "postgresql+psycopg2://postgres:postgres@localhost/postgres",
  isolation_level="AUTOCOMMIT",
)

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]
ALTER ROLE
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 59.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 73.0 MB/s eta 0:00:00

In [3]:
# Завантажуємо SQL розширення
%load_ext sql
# Підключаємося до локальної бази даних postgres
%sql postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
# Перемикаємо стиль оформлення на той, що підтримується поточною версією PrettyTable
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%config SqlMagic.displaylimit = 30

In [4]:
%%sql
SELECT
    current_database() AS curr_db,
    current_user AS curr_user,
    inet_server_port() AS port,
    version() AS postgres_version;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[('postgres', 'postgres', 5432, 'PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit')]

### 1.2. Отримання Olist

In [5]:
KAGGLE_DATASET = "olistbr/brazilian-ecommerce"
MIRROR_GITHUB = "/tmp/olist_mirror"
MIRROR_GITHUB_DATASET = (
    "https://github.com/spdrio/"
    "Brazilian-E-Commerce-Public-Dataset-by-Olist"
)

REQUIRED = [
    "olist_customers_dataset.csv",
    "olist_orders_dataset.csv",
    "olist_order_items_dataset.csv",
    "olist_products_dataset.csv",
    "olist_sellers_dataset.csv",
]

def has_all(d):
    return d and all(os.path.exists(os.path.join(d, f)) for f in REQUIRED)

dataset_dir = None

# Варіант 1: KaggleHub
if dataset_dir is None:
    try:
        d = kagglehub.dataset_download(KAGGLE_DATASET)
        if has_all(d):
            dataset_dir = d
    except Exception as e:
        print(f"KaggleHub unavailable: {e}")

# Варіант 2 / Резерв: публічне дзеркало оригінальних CSV
if dataset_dir is None:
    mirror = MIRROR_GITHUB
    if not os.path.exists(mirror):
        subprocess.run([
            "git",
            "clone",
            "-q",
            "--depth",
            "1",
            MIRROR_GITHUB_DATASET,
            mirror
        ], check=True)
    dataset_dir = os.path.join(mirror, "files")

assert has_all(dataset_dir), "Olist CSV files not found"
print("dataset_dir =", dataset_dir)
for f in REQUIRED:
    print(f"{f:40s} {os.path.getsize(os.path.join(dataset_dir, f)) / 1e6:6.1f} MB")

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
dataset_dir = /kaggle/input/brazilian-ecommerce
olist_customers_dataset.csv                 9.0 MB
olist_orders_dataset.csv                   17.7 MB
olist_order_items_dataset.csv              15.4 MB
olist_products_dataset.csv                  2.4 MB
olist_sellers_dataset.csv                   0.2 MB

### 1.3. Raw-шар: CSV $\rightarrow$ `olist_*_raw` (проміжний шар без constraints)

In [6]:
files = {
    "olist_customers_raw": "olist_customers_dataset.csv",
    "olist_orders_raw": "olist_orders_dataset.csv",
    "olist_order_items_raw": "olist_order_items_dataset.csv",
    "olist_products_raw": "olist_products_dataset.csv",
    "olist_sellers_raw": "olist_sellers_dataset.csv",
}

raw_shapes = {}
for table_name, file_name in files.items():
    path = os.path.join(dataset_dir, file_name)
    df = pd.read_csv(path)
    df.to_sql(
        table_name,
        engine,
        if_exists="replace",
        index=False,
        chunksize=10_000
    )
    raw_shapes[table_name] = df.shape
    print(table_name, df.shape)

olist_customers_raw (99441, 5)
olist_orders_raw (99441, 8)
olist_order_items_raw (112650, 7)
olist_products_raw (32951, 9)
olist_sellers_raw (3095, 4)

### 1.4. Typed-схема з constraints

* `PRIMARY KEY` на природних ключах, складений PK `(order_id, order_item_id)`;
* `FOREIGN KEY` orders $\rightarrow$ customers, items $\rightarrow$ orders/products/sellers;
* `NOT NULL`, `CHECK` на допустимі статуси та невід’ємні числові значення;

Перенесення raw $\rightarrow$ typed через `INSERT ... SELECT` з явними cast-ами. У stub-режимі виконується DDL+seed зі stub-схеми.

In [7]:
%%sql
DROP TABLE IF EXISTS customer_segments CASCADE;
DROP TABLE IF EXISTS seller_score CASCADE;
DROP TABLE IF EXISTS seller_alerts CASCADE;
DROP TABLE IF EXISTS olist_customer_dim CASCADE;
DROP TABLE IF EXISTS olist_order_reviews CASCADE;
DROP TABLE IF EXISTS olist_order_items CASCADE;
DROP TABLE IF EXISTS olist_orders CASCADE;
DROP TABLE IF EXISTS olist_customers CASCADE;
DROP TABLE IF EXISTS olist_products CASCADE;
DROP TABLE IF EXISTS olist_sellers CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);

CREATE INDEX idx_olist_customers_unique_id
    ON olist_customers (customer_unique_id);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (
        product_name_length IS NULL
        OR product_name_length >= 0
    ),
    product_description_length INTEGER CHECK (
        product_description_length IS NULL
        OR product_description_length >= 0
    ),
    product_photos_qty         INTEGER CHECK (
        product_photos_qty IS NULL
        OR product_photos_qty >= 0
    ),
    product_weight_g           INTEGER CHECK (
        product_weight_g IS NULL
        OR product_weight_g >= 0
    ),
    product_length_cm          INTEGER CHECK (
        product_length_cm IS NULL
        OR product_length_cm >= 0
    ),
    product_height_cm          INTEGER CHECK (
        product_height_cm IS NULL
        OR product_height_cm >= 0
    ),
    product_width_cm           INTEGER CHECK (
        product_width_cm IS NULL
        OR product_width_cm >= 0
    )
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.

[]

In [8]:
%%sql
-- Важливий порядок для FOREIGN KEY: спочатку довідники, потім факти
INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,        -- typo 'lenght' саме так у CSV
    product_description_lenght::INTEGER, -- typo 'lenght' саме так у CSV
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;

INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;

ANALYZE
    olist_customers,
    olist_orders,
    olist_order_items,
    olist_products,
    olist_sellers;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
99441 rows affected.
99441 rows affected.
32951 rows affected.
3095 rows affected.
112650 rows affected.
Done.

[]

### 1.5. Smoke-test кількості рядків

In [9]:
%%sql
SELECT
    'customers' AS table_name,
    COUNT(*) AS n_rows
FROM olist_customers
UNION ALL
SELECT
    'orders',
    COUNT(*)
FROM olist_orders
UNION ALL
SELECT
    'order_items',
    COUNT(*)
FROM olist_order_items
UNION ALL
SELECT
    'products',
    COUNT(*)
FROM olist_products
UNION ALL
SELECT
    'sellers',
    COUNT(*)
FROM olist_sellers
ORDER BY table_name;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
5 rows affected.

[('customers', 99441),
 ('order_items', 112650),
 ('orders', 99441),
 ('products', 32951),
 ('sellers', 3095)]

In [10]:
# Порівняння raw vs typed: typed не повинна мати менше рядків, ніж raw.
typed_map = {
    'olist_customers_raw': 'olist_customers',
    'olist_orders_raw': 'olist_orders',
    'olist_order_items_raw': 'olist_order_items',
    'olist_products_raw': 'olist_products',
    'olist_sellers_raw': 'olist_sellers',
}
rows = []
with engine.connect() as conn:
    for raw, typed in typed_map.items():
        n_typed = conn.execute(
            text(f'SELECT COUNT(*) FROM {typed}')
        ).scalar()
        rows.append({
            'table': typed,
            'raw_rows': raw_shapes.get(raw)[0],
            'typed_rows': n_typed,
            'delta': None if raw not in raw_shapes else raw_shapes[raw][0] - n_typed
        })
smoke = pd.DataFrame(rows)
display(smoke)

assert \
    (smoke['delta'] == 0).all(), \
    'typed має менше рядків ніж raw - перевірте cast/constraints'
print(
  '\n'
  'OK: кожен raw-рядок пройшов усі PK/FK/CHECK'
  'constraints -> втрат при типізації немає'
)

               table  raw_rows  typed_rows  delta
0    olist_customers     99441       99441      0
1       olist_orders     99441       99441      0
2  olist_order_items    112650      112650      0
3     olist_products     32951       32951      0
4      olist_sellers      3095        3095      0

OK: кожен raw-рядок пройшов усі PK/FK/CHECKconstraints -> втрат при типізації немає

**Smoke-test.**
> На реальному Olist кількості raw і typed збігаються (`diff = 0`): `INSERT ... SELECT` виконується як одна транзакція на таблицю, тож будь-яке порушення PK/FK/CHECK обірвало б завантаження з помилкою, а не мовчки відкинуло рядки. Тобто дані Olist консистентні.

**Важлива особливість Olist:**
> `customer_id` генерується *на кожне замовлення*, а реальна людина $-$ це `customer_unique_id`. Тому на Olist у більшості клієнтів `frequency = 1`. Ключем feature store за умовою є `customer_id`; для production-моделі варто агрегувати ще й на рівні `customer_unique_id`.

In [11]:
%%sql
-- Data profiling: розподіл статусів
-- (важливо для cancellation_rate) і діапазон дат (для reference_date)
SELECT
    order_status,
    COUNT(*) AS n_orders,
    MIN(order_purchase_timestamp) AS min_ts,
    MAX(order_purchase_timestamp) AS max_ts
FROM olist_orders
GROUP BY order_status
ORDER BY n_orders DESC;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
8 rows affected.

[('delivered', 96478, datetime.datetime(2016, 9, 15, 12, 16, 38), datetime.datetime(2018, 8, 29, 15, 0, 37)),
 ('shipped', 1107, datetime.datetime(2016, 9, 4, 21, 15, 19), datetime.datetime(2018, 9, 3, 9, 6, 57)),
 ('canceled', 625, datetime.datetime(2016, 9, 5, 0, 15, 34), datetime.datetime(2018, 10, 17, 17, 30, 18)),
 ('unavailable', 609, datetime.datetime(2016, 10, 5, 14, 16, 28), datetime.datetime(2018, 8, 21, 12, 21)),
 ('invoiced', 314, datetime.datetime(2016, 10, 4, 13, 2, 10), datetime.datetime(2018, 8, 14, 18, 45, 8)),
 ('processing', 301, datetime.datetime(2016, 10, 5, 22, 44, 13), datetime.datetime(2018, 7, 23, 18, 3, 3)),
 ('created', 5, datetime.datetime(2017, 11, 6, 13, 12, 34), datetime.datetime(2018, 2, 9, 17, 21, 4)),
 ('approved', 2, datetime.datetime(2017, 2, 6, 20, 18, 17), datetime.datetime(2017, 4, 25, 1, 25, 34))]

## 2. CTE-chain feature pipeline (8 named stages)

| Stage | CTE | Відповідальність |
|---|---|---|
| 0 | `reference_date` | стабільна дата відліку = `MAX(order_purchase_timestamp)::date + 1` |
| 1 | `stage1_orders_total` | order-level grain, `order_total` = $\sum \text{(price + freight)}$ |
| 2 | `stage2_rfm` | `recency_days`, `frequency`, `monetary`, `first_order_date` |
| 3 | `stage3_cohort` | `cohort_quarter = DATE_TRUNC('quarter', first_order_date)` |
| 4 | `stage4_rolling_aov` | rolling 30d AVG(`order_total`) $-$ window `RANGE INTERVAL '30 days'` |
| 5 | `stage5_cancel_rate` | `cancellation_rate` |
| 6 | `stage6_category_revenue` | revenue per (customer, category) |
| 7 | `stage7_preferred_category` | top-1 категорія через `ROW_NUMBER()` |

**Вибір `reference_date`, а не `CURRENT_DATE`:**

> датасет історичний (2016–2018). З `CURRENT_DATE` recency зростала б щодня, і та сама модель на тих самих даних давала б інші ознаки $\rightarrow$ нульова відтворюваність. Дата, обчислена з даних, детермінована й одночасно "справедлива" для всіх клієнтів.

> Дизайн-рішення: `monetary` включає й скасовані замовлення (це "намір покупки"), а окремий `cancellation_rate` дозволяє моделі розрізнити такі випадки; клієнти без замовлень отримують нейтральні значення через `COALESCE` (recency = 9999 як sentinel).

In [13]:
%%sql
WITH
reference_date AS (
    -- Stage 0: стабільна reference date, обчислена з самого датасету
    -- (MAX дата покупки + 1 день) -> результат не змінюється з плином часу
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: order-level grain: замовлення + order_total (price + freight) + статус
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM per customer: recency_days (від reference_date), frequency, monetary
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort_quarter = квартал першого замовлення
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day AVG(order_total) per customer (window RANGE 30 days);
    --          rn_recent = 1 позначає останнє замовлення -> актуальне значення ознаки
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation_rate = частка замовлень зі статусом 'canceled'
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue per (customer, product category)
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred_category = top-1 категорія за revenue
    --          (детермінований tie-break за назвою)
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
-- Final: customer-level feature row (LEFT JOIN -> клієнти без замовлень теж отримують рядок)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id
ORDER BY monetary DESC NULLS LAST, c.customer_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
99441 rows affected.

[('1617b1357756262bfa56ab541c47bc16', 'RJ', 384, 1, Decimal('13664.08'), datetime.date(2017, 9, 29), datetime.date(2017, 7, 1), Decimal('13664.08'), Decimal('0.0000'), 'telefonia_fixa', Decimal('13664.08')),
 ('ec5b2ba62e574342386871631fafd3fc', 'ES', 95, 1, Decimal('7274.88'), datetime.date(2018, 7, 15), datetime.date(2018, 7, 1), Decimal('7274.88'), Decimal('0.0000'), 'telefonia_fixa', Decimal('7274.88')),
 ('c6e2731c5b391845f6800c97401a43a9', 'MS', 613, 1, Decimal('6929.31'), datetime.date(2017, 2, 12), datetime.date(2017, 1, 1), Decimal('6929.31'), Decimal('0.0000'), 'utilidades_domesticas', Decimal('6929.31')),
 ('f48d464a0baaea338cb25f816991ab1f', 'ES', 85, 1, Decimal('6922.21'), datetime.date(2018, 7, 25), datetime.date(2018, 7, 1), Decimal('6922.21'), Decimal('0.0000'), 'pcs', Decimal('6922.21')),
 ('3fd6777bbce08a352fddd04e4a7cc8f6', 'SP', 512, 1, Decimal('6726.66'), datetime.date(2017, 5, 24), datetime.date(2017, 4, 1), Decimal('6726.66'), Decimal('0.0000'), 'artes', Decimal('6726.66')),
 ('05455dfa7cd02f13d132aa7a6a9729c6', 'MG', 328, 1, Decimal('6081.54'), datetime.date(2017, 11, 24), datetime.date(2017, 10, 1), Decimal('6081.54'), Decimal('0.0000'), 'agro_industria_e_comercio', Decimal('6081.54')),
 ('df55c14d1476a9a3467f131269c2477f', 'RJ', 565, 1, Decimal('4950.34'), datetime.date(2017, 4, 1), datetime.date(2017, 4, 1), Decimal('4950.34'), Decimal('0.0000'), 'eletroportateis', Decimal('4950.34')),
 ('e0a2412720e9ea4f26c1ac985f6a7358', 'GO', 98, 1, Decimal('4809.44'), datetime.date(2018, 7, 12), datetime.date(2018, 7, 1), Decimal('4809.44'), Decimal('1.0000'), 'cool_stuff', Decimal('4809.44')),
 ('24bbf5fd2f2e1b359ee7de94defc4a15', 'SP', 548, 1, Decimal('4764.34'), datetime.date(2017, 4, 18), datetime.date(2017, 4, 1), Decimal('4764.34'), Decimal('0.0000'), 'eletroportateis', Decimal('4764.34')),
 ('3d979689f636322c62418b6346b1c6d2', 'PB', 118, 1, Decimal('4681.78'), datetime.date(2018, 6, 22), datetime.date(2018, 4, 1), Decimal('4681.78'), Decimal('0.0000'), 'pcs', Decimal('4681.78')),
 ('1afc82cd60e303ef09b4ef9837c9505c', 'SP', 76, 1, Decimal('4513.32'), datetime.date(2018, 8, 3), datetime.date(2018, 7, 1), Decimal('4513.32'), Decimal('0.0000'), 'instrumentos_musicais', Decimal('4513.32')),
 ('cc803a2c412833101651d3f90ca7de24', 'RJ', 140, 1, Decimal('4445.50'), datetime.date(2018, 5, 31), datetime.date(2018, 4, 1), Decimal('4445.50'), Decimal('0.0000'), 'relogios_presentes', Decimal('4445.50')),
 ('926b6a6fb8b6081e00b335edaf578d35', 'DF', 548, 1, Decimal('4194.76'), datetime.date(2017, 4, 18), datetime.date(2017, 4, 1), Decimal('4194.76'), Decimal('0.0000'), 'eletroportateis', Decimal('4194.76')),
 ('35a413c7ca3c69756cb75867d6311c0d', 'MG', 203, 1, Decimal('4175.26'), datetime.date(2018, 3, 29), datetime.date(2018, 1, 1), Decimal('4175.26'), Decimal('0.0000'), 'consoles_games', Decimal('4175.26')),
 ('e9b0d0eb3015ef1c9ce6cf5b9dcbee9f', 'MG', 81, 1, Decimal('4163.51'), datetime.date(2018, 7, 29), datetime.date(2018, 7, 1), Decimal('4163.51'), Decimal('0.0000'), 'esporte_lazer', Decimal('4163.51')),
 ('3be2c536886b2ea4668eced3a80dd0bb', 'PA', 621, 1, Decimal('4042.74'), datetime.date(2017, 2, 4), datetime.date(2017, 1, 1), Decimal('4042.74'), Decimal('0.0000'), '(unknown)', Decimal('4042.74')),
 ('eb7a157e8da9c488cd4ddc48711f1097', 'SP', 135, 1, Decimal('4034.44'), datetime.date(2018, 6, 5), datetime.date(2018, 4, 1), Decimal('4034.44'), Decimal('0.0000'), 'bebes', Decimal('4034.44')),
 ('c6695e3b1e48680db36b487419fb0398', 'SP', 579, 1, Decimal('4016.91'), datetime.date(2017, 3, 18), datetime.date(2017, 1, 1), Decimal('4016.91'), Decimal('0.0000'), 'relogios_presentes', Decimal('4016.91')),
 ('31e83c01fce824d0ff786fcd48dad009', 'RJ', 157, 1, Decimal('3979.55'), datetime.date(2018, 5, 14), datetime.date(2018, 4, 1), Decimal('3979.55'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('3979.55')),
 ('addc91fdf9c2b3045497b57fc710e820', 'MG', 265, 1, Decimal('3826.80'), datetime.date(2018, 1, 26), datetime.date(2018, 1, 1), Decimal('3826.80'), Decimal('0.0000'), 'esporte_lazer', Decimal('3826.80')),
 ('19b32919fa1198aefc0773ee2e46e693', 'PE', 211, 1, Decimal('3792.59'), datetime.date(2018, 3, 21), datetime.date(2018, 1, 1), Decimal('3792.59'), Decimal('0.0000'), 'relogios_presentes', Decimal('3792.59')),
 ('66657bf1753d82d0a76f2c4719ab8b85', 'DF', 615, 1, Decimal('3736.22'), datetime.date(2017, 2, 10), datetime.date(2017, 1, 1), Decimal('3736.22'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3736.22')),
 ('7d03bf20fa96e80468bbf678eebbcb3f', 'SC', 526, 1, Decimal('3666.42'), datetime.date(2017, 5, 10), datetime.date(2017, 4, 1), Decimal('3666.42'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3666.42')),
 ('39d6658037b1b5a07d0a24d423f0bd19', 'DF', 604, 1, Decimal('3602.47'), datetime.date(2017, 2, 21), datetime.date(2017, 1, 1), Decimal('3602.47'), Decimal('0.0000'), 'pcs', Decimal('3602.47')),
 ('e7c905bf4bb13543e8df947af4f3d9e9', 'SP', 192, 1, Decimal('3526.46'), datetime.date(2018, 4, 9), datetime.date(2018, 4, 1), Decimal('3526.46'), Decimal('0.0000'), 'pcs', Decimal('3526.46')),
 ('3c7c62e8d38fb18a33a45db8021f2d69', 'PB', 104, 1, Decimal('3406.47'), datetime.date(2018, 7, 6), datetime.date(2018, 7, 1), Decimal('3406.47'), Decimal('0.0000'), 'industria_comercio_e_negocios', Decimal('3406.47')),
 ('0b16ce67087d02bf833c807e82b1992b', 'BA', 249, 1, Decimal('3358.24'), datetime.date(2018, 2, 11), datetime.date(2018, 1, 1), Decimal('3358.24'), Decimal('0.0000'), 'telefonia_fixa', Decimal('3358.24')),
 ('803cd9b04f9cd252c6a83a2ecdbc22c3', 'MG', 64, 1, Decimal('3351.35'), datetime.date(2018, 8, 15), datetime.date(2018, 7, 1), Decimal('3351.35'), Decimal('0.0000'), 'esporte_lazer', Decimal('3351.35')),
 ('46bb3c0b1a65c8399d0363cefbcc4f37', 'RS', 305, 1, Decimal('3297.40'), datetime.date(2017, 12, 17), datetime.date(2017, 10, 1), Decimal('3297.40'), Decimal('0.0000'), 'beleza_saude', Decimal('3297.40')),
 ('a7ea318cbe9df2ec79ab37cd7ca2135d', 'SP', 133, 1, Decimal('3256.14'), datetime.date(2018, 6, 7), datetime.date(2018, 4, 1), Decimal('3256.14'), Decimal('0.0000'), 'consoles_games', Decimal('3256.14')),
 ('f7622098214b4634b7fe7eee269b5426', 'MT', 139, 1, Decimal('3242.84'), datetime.date(2018, 6, 1), datetime.date(2018, 4, 1), Decimal('3242.84'), Decimal('0.0000'), 'sinalizacao_e_seguranca', Decimal('3242.84')),
 ('7e7d2271d6f55b03b0bd4615c5f2de6e', 'SC', 174, 1, Decimal('3209.72'), datetime.date(2018, 4, 27), datetime.date(2018, 4, 1), Decimal('3209.72'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('3209.72')),
 ('71901689c5f3e5adc27b1dd16b33f0b8', 'MA', 149, 1, Decimal('3195.74'), datetime.date(2018, 5, 22), datetime.date(2018, 4, 1), Decimal('3195.74'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3195.74')),
 ('c26acf0451e0f8ec1f5218731b9a51cf', 'PE', 332, 1, Decimal('3184.55'), datetime.date(2017, 11, 20), datetime.date(2017, 10, 1), Decimal('3184.55'), Decimal('0.0000'), 'agro_industria_e_comercio', Decimal('3184.55')),
 ('26dcb450c4b5b390e79e6d5d0f2c6535', 'SC', 86, 1, Decimal('3184.34'), datetime.date(2018, 7, 24), datetime.date(2018, 7, 1), Decimal('3184.34'), Decimal('0.0000'), 'cool_stuff', Decimal('3184.34')),
 ('a95f4bbcf95262b073e4afa481b59ff8', 'MG', 251, 1, Decimal('3155.82'), datetime.date(2018, 2, 9), datetime.date(2018, 1, 1), Decimal('3155.82'), Decimal('0.0000'), 'construcao_ferramentas_seguranca', Decimal('3155.82')),
 ('0a209a88c2e3dc2981c79ad85c558059', 'PR', 378, 1, Decimal('3126.50'), datetime.date(2017, 10, 5), datetime.date(2017, 10, 1), Decimal('3126.50'), Decimal('0.0000'), 'pcs', Decimal('3126.50')),
 ('10a86619816f9d2afce3f45b04aabc71', 'RJ', 373, 1, Decimal('3126.50'), datetime.date(2017, 10, 10), datetime.date(2017, 10, 1), Decimal('3126.50'), Decimal('0.0000'), 'pcs', Decimal('3126.50')),
 ('6152fbfc8a92ee25fd821740bd33b089', 'BA', 129, 1, Decimal('3122.72'), datetime.date(2018, 6, 11), datetime.date(2018, 4, 1), Decimal('3122.72'), Decimal('0.0000'), 'pcs', Decimal('3122.72')),
 ('c03dfaf5db49d8583edbb5627f92058d', 'SP', 64, 1, Decimal('3076.13'), datetime.date(2018, 8, 15), datetime.date(2018, 7, 1), Decimal('3076.13'), Decimal('0.0000'), 'esporte_lazer', Decimal('3076.13')),
 ('4312e816d88fa8bdb6246878f61cdad5', 'BA', 500, 1, Decimal('3048.27'), datetime.date(2017, 6, 5), datetime.date(2017, 4, 1), Decimal('3048.27'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3048.27')),
 ('3a4e4932f3e6976dd966f1d3c044d49e', 'MS', 589, 1, Decimal('3044.12'), datetime.date(2017, 3, 8), datetime.date(2017, 1, 1), Decimal('3044.12'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3044.12')),
 ('d7c94e22bfd332eb29b0f5badc3ce103', 'MG', 577, 1, Decimal('3042.36'), datetime.date(2017, 3, 20), datetime.date(2017, 1, 1), Decimal('3042.36'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3042.36')),
 ('8dd4c93bfbebe2a77657d46ef959a7ac', 'RJ', 469, 1, Decimal('3041.73'), datetime.date(2017, 7, 6), datetime.date(2017, 7, 1), Decimal('3041.73'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3041.73')),
 ('fd78e5e3abdc375368456fe738694c00', 'SP', 570, 1, Decimal('3024.08'), datetime.date(2017, 3, 27), datetime.date(2017, 1, 1), Decimal('3024.08'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3024.08')),
 ('1ff773612ab8934db89fd5afa8afe506', 'RJ', 182, 1, Decimal('3018.60'), datetime.date(2018, 4, 19), datetime.date(2018, 4, 1), Decimal('3018.60'), Decimal('0.0000'), 'bebidas', Decimal('3018.60')),
 ('101c8d91278c4de9001566d27033f673', 'SP', 625, 1, Decimal('3016.01'), datetime.date(2017, 1, 31), datetime.date(2017, 1, 1), Decimal('3016.01'), Decimal('0.0000'), 'relogios_presentes', Decimal('3016.01')),
 ('9d4ba8752b5b737f45da0544b669552a', 'BA', 561, 1, Decimal('3009.53'), datetime.date(2017, 4, 5), datetime.date(2017, 4, 1), Decimal('3009.53'), Decimal('0.0000'), 'informatica_acessorios', Decimal('3009.53')),
 ('a8f345f82667eb421151dc7626147636', 'SC', 174, 1, Decimal('3005.06'), datetime.date(2018, 4, 27), datetime.date(2018, 4, 1), Decimal('3005.06'), Decimal('0.0000'), 'bebes', Decimal('3005.06')),
 ('a5c69c3bf293d341b6a56a4b7307c529', 'SC', 214, 1, Decimal('2960.05'), datetime.date(2018, 3, 18), datetime.date(2018, 1, 1), Decimal('2960.05'), Decimal('0.0000'), 'portateis_casa_forno_e_cafe', Decimal('2960.05')),
 ('a244afc7a1ec53f1aad296d1cd6e91ba', 'SP', 332, 1, Decimal('2938.17'), datetime.date(2017, 11, 20), datetime.date(2017, 10, 1), Decimal('2938.17'), Decimal('0.0000'), 'beleza_saude', Decimal('2938.17')),
 ('f41666558f4e35056a445c27c2ac3d8b', 'SP', 352, 1, Decimal('2913.48'), datetime.date(2017, 10, 31), datetime.date(2017, 10, 1), Decimal('2913.48'), Decimal('0.0000'), 'pcs', Decimal('2913.48')),
 ('ed583a2a1eaf0dedc33af816153e8b8c', 'PB', 108, 1, Decimal('2844.96'), datetime.date(2018, 7, 2), datetime.date(2018, 7, 1), Decimal('2844.96'), Decimal('0.0000'), 'sinalizacao_e_seguranca', Decimal('2844.96')),
 ('9f9717a71bd8f6e5600b4faad20c20fb', 'MG', 196, 1, Decimal('2838.22'), datetime.date(2018, 4, 5), datetime.date(2018, 4, 1), Decimal('2838.22'), Decimal('0.0000'), 'beleza_saude', Decimal('2838.22')),
 ('55fd5d10a5036383fe19af015d2e5a80', 'DF', 142, 1, Decimal('2828.42'), datetime.date(2018, 5, 29), datetime.date(2018, 4, 1), Decimal('2828.42'), Decimal('0.0000'), 'beleza_saude', Decimal('2828.42')),
 ('1be0dd2f660a5a04ee20d608075f1b83', 'PR', 520, 1, Decimal('2827.00'), datetime.date(2017, 5, 16), datetime.date(2017, 4, 1), Decimal('2827.00'), Decimal('0.0000'), 'esporte_lazer', Decimal('2827.00')),
 ('fced842c7dad61e8ce47b49229659718', 'SP', 173, 1, Decimal('2818.74'), datetime.date(2018, 4, 28), datetime.date(2018, 4, 1), Decimal('2818.74'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('2818.74')),
 ('8e2c57611e09e143ec4ab76e38033bef', 'GO', 527, 1, Decimal('2794.50'), datetime.date(2017, 5, 9), datetime.date(2017, 4, 1), Decimal('2794.50'), Decimal('0.0000'), '(unknown)', Decimal('2794.50')),
 ('97dd9c6923b3237b650f1f4f3f2145ad', 'SP', 140, 1, Decimal('2787.87'), datetime.date(2018, 5, 31), datetime.date(2018, 4, 1), Decimal('2787.87'), Decimal('0.0000'), 'beleza_saude', Decimal('2787.87')),
 ('8401401a8752eb431189e021b8009e37', 'TO', 479, 1, Decimal('2784.16'), datetime.date(2017, 6, 26), datetime.date(2017, 4, 1), Decimal('2784.16'), Decimal('0.0000'), 'informatica_acessorios', Decimal('2784.16')),
 ('e5df9583ddbe3f4f3857d9b667dfa609', 'BA', 161, 1, Decimal('2759.95'), datetime.date(2018, 5, 10), datetime.date(2018, 4, 1), Decimal('2759.95'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('2759.95')),
 ('5f87c05477db2d22c63b718299c9c03e', 'MG', 325, 1, Decimal('2759.88'), datetime.date(2017, 11, 27), datetime.date(2017, 10, 1), Decimal('2759.88'), Decimal('0.0000'), 'informatica_acessorios', Decimal('2759.88')),
 ('3f083b9f62e687be8d84684c7d54c8db', 'RJ', 560, 1, Decimal('2751.24'), datetime.date(2017, 4, 6), datetime.date(2017, 4, 1), Decimal('2751.24'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('2751.24')),
 ('08dc68ad9ab343289844fa36f6963b8f', 'SP', 320, 1, Decimal('2734.66'), datetime.date(2017, 12, 2), datetime.date(2017, 10, 1), Decimal('2734.66'), Decimal('0.0000'), 'relogios_presentes', Decimal('2734.66')),
 ('19365ad6a18ccf1baf6eb71c30651096', 'CE', 487, 1, Decimal('2734.11'), datetime.date(2017, 6, 18), datetime.date(2017, 4, 1), Decimal('2734.11'), Decimal('0.0000'), 'eletroportateis', Decimal('2734.11')),
 ('695476b5848d64ba0875324c88390206', 'RJ', 301, 1, Decimal('2733.63'), datetime.date(2017, 12, 21), datetime.date(2017, 10, 1), Decimal('2733.63'), Decimal('0.0000'), 'informatica_acessorios', Decimal('2733.63')),
 ('2e0339ff984d6f41f11dfdbc7c93dcda', 'BA', 307, 1, Decimal('2732.06'), datetime.date(2017, 12, 15), datetime.date(2017, 10, 1), Decimal('2732.06'), Decimal('0.0000'), 'pcs', Decimal('2732.06')),
 ('f08306b95370e8d5f0d97b71229284b6', 'PR', 80, 1, Decimal('2713.36'), datetime.date(2018, 7, 30), datetime.date(2018, 7, 1), Decimal('2713.36'), Decimal('0.0000'), 'utilidades_domesticas', Decimal('2713.36')),
 ('f2c743697f9b2ff2902df23a16582d80', 'SC', 66, 1, Decimal('2713.36'), datetime.date(2018, 8, 13), datetime.date(2018, 7, 1), Decimal('2713.36'), Decimal('0.0000'), 'utilidades_domesticas', Decimal('2713.36')),
 ('3690e975641f01bd07ad635f03dbb894', 'BA', 428, 1, Decimal('2692.82'), datetime.date(2017, 8, 16), datetime.date(2017, 7, 1), Decimal('2692.82'), Decimal('1.0000'), 'cool_stuff', Decimal('2692.82')),
 ('b177ef267a4377b77e0620d1a7f08dce', 'SP', 500, 1, Decimal('2681.29'), datetime.date(2017, 6, 5), datetime.date(2017, 4, 1), Decimal('2681.29'), Decimal('0.0000'), 'cool_stuff', Decimal('2681.29')),
 ('b1c28f9b72d07054b64d09e487b5021c', 'SP', 503, 1, Decimal('2681.29'), datetime.date(2017, 6, 2), datetime.date(2017, 4, 1), Decimal('2681.29'), Decimal('0.0000'), 'cool_stuff', Decimal('2681.29')),
 ('279ca766397588e704abddd56d2dc131', 'SC', 150, 1, Decimal('2647.76'), datetime.date(2018, 5, 21), datetime.date(2018, 4, 1), Decimal('2647.76'), Decimal('0.0000'), 'eletronicos', Decimal('2647.76')),
 ('7e95832184f874c220b8ebffa750837d', 'SP', 160, 1, Decimal('2638.64'), datetime.date(2018, 5, 11), datetime.date(2018, 4, 1), Decimal('2638.64'), Decimal('0.0000'), 'informatica_acessorios', Decimal('2638.64')),
 ('1ca6f90a61cf75c002a0d690261a0e4c', 'MG', 480, 1, Decimal('2627.09'), datetime.date(2017, 6, 25), datetime.date(2017, 4, 1), Decimal('2627.09'), Decimal('0.0000'), 'cool_stuff', Decimal('2627.09')),
 ('0c5292f5e3690805390efddf53935915', 'SP', 595, 1, Decimal('2626.07'), datetime.date(2017, 3, 2), datetime.date(2017, 1, 1), Decimal('2626.07'), Decimal('0.0000'), 'esporte_lazer', Decimal('2626.07')),
 ('349509b216bd5ec11c5fae929fd13595', 'RJ', 565, 1, Decimal('2621.29'), datetime.date(2017, 4, 1), datetime.date(2017, 4, 1), Decimal('2621.29'), Decimal('0.0000'), 'eletroportateis', Decimal('2621.29')),
 ('1fb8ff22dad231d26fc7ecde2e2dc27a', 'DF', 163, 1, Decimal('2616.00'), datetime.date(2018, 5, 8), datetime.date(2018, 4, 1), Decimal('2616.00'), Decimal('0.0000'), 'ferramentas_jardim', Decimal('2616.00')),
 ('53e644c7c57416bdaf0409e656ee8b0a', 'SP', 139, 1, Decimal('2607.09'), datetime.date(2018, 6, 1), datetime.date(2018, 4, 1), Decimal('2607.09'), Decimal('0.0000'), 'eletroportateis', Decimal('2607.09')),
 ('e9859fbdff7d26c36c228cf60796e844', 'SP', 560, 1, Decimal('2606.01'), datetime.date(2017, 4, 6), datetime.date(2017, 4, 1), Decimal('2606.01'), Decimal('0.0000'), 'eletroportateis', Decimal('2606.01')),
 ('9c5d7103954595e173781530b10d02e4', 'MG', 217, 1, Decimal('2590.61'), datetime.date(2018, 3, 15), datetime.date(2018, 1, 1), Decimal('2590.61'), Decimal('0.0000'), 'eletronicos', Decimal('2590.61')),
 ('35698a7b9ae42369b9f45a53000f85f3', 'RJ', 579, 1, Decimal('2574.38'), datetime.date(2017, 3, 18), datetime.date(2017, 1, 1), Decimal('2574.38'), Decimal('0.0000'), 'pet_shop', Decimal('2574.38')),
 ('03a6f3a3935165f5d26f4797ba6039bb', 'SP', 560, 1, Decimal('2566.90'), datetime.date(2017, 4, 6), datetime.date(2017, 4, 1), Decimal('2566.90'), Decimal('0.0000'), 'telefonia_fixa', Decimal('2566.90')),
 ('9537f2addba8448428a3fd1a1add0656', 'SP', 152, 1, Decimal('2564.65'), datetime.date(2018, 5, 19), datetime.date(2018, 4, 1), Decimal('2564.65'), Decimal('0.0000'), 'eletronicos', Decimal('2564.65')),
 ('3696afd6fae4a1f36fcbc3db8f3d6640', 'SP', 70, 1, Decimal('2512.53'), datetime.date(2018, 8, 9), datetime.date(2018, 7, 1), Decimal('2512.53'), Decimal('0.0000'), 'utilidades_domesticas', Decimal('2512.53')),
 ('cb3724d7cb7db46b65cfd1e7c16c0df5', 'MT', 447, 1, Decimal('2487.24'), datetime.date(2017, 7, 28), datetime.date(2017, 7, 1), Decimal('2487.24'), Decimal('0.0000'), 'beleza_saude', Decimal('2487.24')),
 ('6361b9f3b85d41860bfa28292e052bde', 'SC', 435, 1, Decimal('2480.58'), datetime.date(2017, 8, 9), datetime.date(2017, 7, 1), Decimal('2480.58'), Decimal('0.0000'), 'automotivo', Decimal('2480.58')),
 ('233d97d412c7f4bb8d857ec922c0317f', 'SP', 355, 1, Decimal('2467.33'), datetime.date(2017, 10, 28), datetime.date(2017, 10, 1), Decimal('2467.33'), Decimal('0.0000'), 'agro_industria_e_comercio', Decimal('2467.33')),
 ('b9da524b08224eaff1bf76ef4d4299ac', 'SP', 146, 1, Decimal('2467.17'), datetime.date(2018, 5, 25), datetime.date(2018, 4, 1), Decimal('2467.17'), Decimal('0.0000'), 'pcs', Decimal('2467.17')),
 ('68f692d1f39843a16d9319a7306b6b10', 'SP', 177, 1, Decimal('2457.44'), datetime.date(2018, 4, 24), datetime.date(2018, 4, 1), Decimal('2457.44'), Decimal('0.0000'), 'telefonia', Decimal('2457.44')),
 ('548692bdcbd6e3683ff306ac9d8418d6', 'RS', 69, 1, Decimal('2455.12'), datetime.date(2018, 8, 10), datetime.date(2018, 7, 1), Decimal('2455.12'), Decimal('0.0000'), 'eletrodomesticos_2', Decimal('2455.12')),
 ('cdecc5d1f7fc375b1138e8b5f496fd69', 'RO', 322, 1, Decimal('2452.12'), datetime.date(2017, 11, 30), datetime.date(2017, 10, 1), Decimal('2452.12'), Decimal('0.0000'), 'relogios_presentes', Decimal('2452.12')),
 ('177ba55869da8001fcca079af0b85832', 'PB', 82, 1, Decimal('2438.51'), datetime.date(2018, 7, 28), datetime.date(2018, 7, 1), Decimal('2438.51'), Decimal('0.0000'), 'relogios_presentes', Decimal('2438.51')),
 ('b76816b61d8043a98db57875437da6b5', 'RJ', 328, 1, Decimal('2429.68'), datetime.date(2017, 11, 24), datetime.date(2017, 10, 1), Decimal('2429.68'), Decimal('0.0000'), 'relogios_presentes', Decimal('2429.68')),
 ('2b7ae7a532ff538ce88f6bfdd2cb564c', 'PR', 73, 1, Decimal('2419.20'), datetime.date(2018, 8, 6), datetime.date(2018, 7, 1), Decimal('2419.20'), Decimal('1.0000'), 'eletrodomesticos_2', Decimal('2419.20')),
 ('30ab7e538292e6130a456c371778d595', 'MG', 327, 1, Decimal('2416.00'), datetime.date(2017, 11, 25), datetime.date(2017, 10, 1), Decimal('2416.00'), Decimal('0.0000'), 'instrumentos_musicais', Decimal('2416.00')),
 ('24301c6ce48874a51221d4e5584a7885', 'RS', 98, 1, Decimal('2404.72'), datetime.date(2018, 7, 12), datetime.date(2018, 7, 1), Decimal('2404.72'), Decimal('1.0000'), 'cool_stuff', Decimal('2404.72')),

### 2.1. Перевірка окремих stages (single responsibility $\rightarrow$ кожен етап можна протестувати окремо)

In [14]:
%%sql
-- Stage 0 + Stage 3: reference date і розподіл когорт
WITH
reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date FROM olist_orders
),
first_orders AS (
    SELECT
        customer_id,
        MIN(order_purchase_timestamp)::DATE AS first_order_date
    FROM olist_orders
    GROUP BY customer_id
)
SELECT
    (SELECT as_of_date FROM reference_date) AS as_of_date,
    DATE_TRUNC('quarter', first_order_date)::DATE AS cohort_quarter,
    COUNT(*) AS n_customers
FROM first_orders
GROUP BY 2
ORDER BY 2;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
10 rows affected.

[(datetime.date(2018, 10, 18), datetime.date(2016, 7, 1), 4),
 (datetime.date(2018, 10, 18), datetime.date(2016, 10, 1), 325),
 (datetime.date(2018, 10, 18), datetime.date(2017, 1, 1), 5262),
 (datetime.date(2018, 10, 18), datetime.date(2017, 4, 1), 9349),
 (datetime.date(2018, 10, 18), datetime.date(2017, 7, 1), 12642),
 (datetime.date(2018, 10, 18), datetime.date(2017, 10, 1), 17848),
 (datetime.date(2018, 10, 18), datetime.date(2018, 1, 1), 21208),
 (datetime.date(2018, 10, 18), datetime.date(2018, 4, 1), 19979),
 (datetime.date(2018, 10, 18), datetime.date(2018, 7, 1), 12820),
 (datetime.date(2018, 10, 18), datetime.date(2018, 10, 1), 4)]

In [15]:
%%sql
-- Stage 4 (unit-check): семантика вікна RANGE '30 days'.
-- На Olist customer_id = 1 замовлення, тому для наочності партиціюємо за customer_unique_id
-- (реальна людина з кількома замовленнями). Логіка вікна та сама, що в pipeline.
WITH stage1_orders_total AS (
    SELECT
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp AS order_ts,
        COALESCE(
          SUM(COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)),
          0
        )::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    JOIN olist_customers AS c
        ON c.customer_id = o.customer_id
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        c.customer_unique_id,
        o.order_id,
        o.order_purchase_timestamp
),
multi AS (
    SELECT
        customer_unique_id
    FROM stage1_orders_total
    GROUP BY customer_unique_id
    HAVING COUNT(*) >= 3
    ORDER BY COUNT(*) DESC, customer_unique_id LIMIT 2
)
SELECT
    s.customer_unique_id,
    s.order_id,
    s.order_ts,
    s.order_total,
    AVG(s.order_total) OVER (
        PARTITION BY s.customer_unique_id
        ORDER BY s.order_ts
        RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
    )::NUMERIC(12, 2) AS avg_order_value_30d
FROM stage1_orders_total AS s
JOIN multi
    USING (customer_unique_id)
ORDER BY s.customer_unique_id, s.order_ts;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
26 rows affected.

[('3e43e6105506432c953e165fb2acf44c', 'ed0b6f8c8617370e53735a5d963bb5b6', datetime.datetime(2017, 9, 18, 18, 53, 15), Decimal('98.73'), Decimal('98.73')),
 ('3e43e6105506432c953e165fb2acf44c', 'e23ad32d5c15d9ad308baddc6262afea', datetime.datetime(2017, 12, 1, 9, 30, 36), Decimal('115.40'), Decimal('115.40')),
 ('3e43e6105506432c953e165fb2acf44c', '1124c329070977fbd414f046bba149d7', datetime.datetime(2017, 12, 1, 22, 37, 41), Decimal('65.10'), Decimal('90.25')),
 ('3e43e6105506432c953e165fb2acf44c', '826b47e4cd7bba4e4c6fa5485f898b74', datetime.datetime(2017, 12, 1, 22, 37, 42), Decimal('364.18'), Decimal('181.56')),
 ('3e43e6105506432c953e165fb2acf44c', 'caf10b4f81696bae84a2448c0767b3b0', datetime.datetime(2018, 1, 11, 10, 56, 15), Decimal('132.95'), Decimal('132.95')),
 ('3e43e6105506432c953e165fb2acf44c', '70863e8ef99613bbc8f854807d187ea7', datetime.datetime(2018, 2, 12, 10, 12, 54), Decimal('130.58'), Decimal('130.58')),
 ('3e43e6105506432c953e165fb2acf44c', 'f75455b78762d30c7e663172f18dbcbe', datetime.datetime(2018, 2, 12, 10, 12, 55), Decimal('65.87'), Decimal('98.23')),
 ('3e43e6105506432c953e165fb2acf44c', 'ed92e8596b1e39671065510a4f5b0920', datetime.datetime(2018, 2, 20, 10, 45, 22), Decimal('76.17'), Decimal('90.87')),
 ('3e43e6105506432c953e165fb2acf44c', 'ff89ef7b3952bba5ac06d61c4a79ffbe', datetime.datetime(2018, 2, 27, 18, 36, 39), Decimal('123.69'), Decimal('99.08')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '5d848f3d93a493c1c8955e018240e7ca', datetime.datetime(2017, 5, 15, 23, 30, 3), Decimal('22.77'), Decimal('22.77')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '369634708db140c5d2c4e365882c443a', datetime.datetime(2017, 6, 18, 22, 56, 48), Decimal('51.75'), Decimal('51.75')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '5837a2c844decae8a778657425f6d664', datetime.datetime(2017, 7, 17, 22, 11, 13), Decimal('0.00'), Decimal('25.88')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '4f62d593acae92cea3c5662c76122478', datetime.datetime(2017, 7, 18, 23, 10, 58), Decimal('21.77'), Decimal('10.89')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'bf92c69b7cc70f7fc2c37de43e366173', datetime.datetime(2017, 7, 24, 22, 11, 50), Decimal('166.71'), Decimal('62.83')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '519203404f6116d406a970763ee75799', datetime.datetime(2017, 8, 5, 8, 59, 43), Decimal('81.89'), Decimal('67.59')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'e3071b7624445af6e4f3a1b23718667d', datetime.datetime(2017, 9, 5, 22, 14, 52), Decimal('51.75'), Decimal('51.75')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'cd4b336a02aacabd0ef22f6db711f95e', datetime.datetime(2017, 10, 18, 23, 25, 4), Decimal('37.77'), Decimal('37.77')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '89d9b111d2b990deb5f5f9769f92800b', datetime.datetime(2017, 10, 29, 16, 58, 2), Decimal('21.77'), Decimal('29.77')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'b850a16d8faf65a74c51287ef34379ce', datetime.datetime(2017, 11, 22, 20, 1, 53), Decimal('21.77'), Decimal('21.77')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '23427a6bd9f8fd1b51f1b1e5cc186ab8', datetime.datetime(2018, 5, 21, 22, 44, 31), Decimal('53.38'), Decimal('53.38')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '6bdf325f0966e3056651285c0aed5aad', datetime.datetime(2018, 5, 22, 23, 8, 55), Decimal('62.95'), Decimal('58.17')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '838f8e96cf584a1d8d22eaf7143c7772', datetime.datetime(2018, 7, 4, 22, 35, 13), Decimal('30.41'), Decimal('30.41')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', '112eb6f37f1b9dabbced368fbbc6c9ef', datetime.datetime(2018, 7, 23, 21, 53, 2), Decimal('107.85'), Decimal('69.13')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'c2213109a2cc0e75d55585b7aaac6d97', datetime.datetime(2018, 8, 7, 23, 32, 14), Decimal('34.44'), Decimal('71.15')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'a1a6eadae352582010f449d8527b55f3', datetime.datetime(2018, 8, 18, 12, 39, 19), Decimal('96.40'), Decimal('79.56')),
 ('8d50f5eadf50201ccdcedfb9e2ac8455', 'd3582fd5ccccd9cb229a63dfb417c86f', datetime.datetime(2018, 8, 20, 19, 14, 26), Decimal('38.66'), Decimal('69.34'))]

In [16]:
%%sql
-- Data-quality checks для фінального feature-набору
WITH features AS (
    WITH
    reference_date AS (
        -- Stage 0: стабільна reference date, обчислена з самого датасету
        -- (MAX дата покупки + 1 день) -> результат не змінюється з плином часу
        SELECT
            (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
        FROM olist_orders
    ),
    stage1_orders_total AS (
        -- Stage 1: order-level grain: замовлення + order_total (price + freight) + статус
        SELECT
            o.customer_id,
            o.order_id,
            o.order_status,
            o.order_purchase_timestamp AS order_ts,
            o.order_purchase_timestamp::DATE AS order_date,
            COALESCE(SUM(
                COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
            ), 0)::NUMERIC(12, 2) AS order_total
        FROM olist_orders AS o
        LEFT JOIN olist_order_items AS oi
            ON oi.order_id = o.order_id
        GROUP BY
            o.customer_id,
            o.order_id,
            o.order_status,
            o.order_purchase_timestamp
    ),
    stage2_rfm AS (
        -- Stage 2: RFM per customer: recency_days (від reference_date), frequency, monetary
        SELECT
            s.customer_id,
            (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
            COUNT(*) AS frequency,
            SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
            MIN(s.order_date) AS first_order_date
        FROM stage1_orders_total AS s
        CROSS JOIN reference_date AS rd
        GROUP BY s.customer_id, rd.as_of_date
    ),
    stage3_cohort AS (
        -- Stage 3: cohort_quarter = квартал першого замовлення
        SELECT
            r.*,
            DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
        FROM stage2_rfm AS r
    ),
    stage4_rolling_aov AS (
        -- Stage 4: rolling 30-day AVG(order_total) per customer (window RANGE 30 days);
        --          rn_recent = 1 позначає останнє замовлення -> актуальне значення ознаки
        SELECT
            s.customer_id,
            s.order_id,
            s.order_ts,
            s.order_total,
            AVG(s.order_total) OVER (
                PARTITION BY s.customer_id
                ORDER BY s.order_ts
                RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
            )::NUMERIC(12, 2) AS avg_order_value_30d,
            ROW_NUMBER() OVER (
                PARTITION BY s.customer_id
                ORDER BY s.order_ts DESC, s.order_id DESC
            ) AS rn_recent
        FROM stage1_orders_total AS s
    ),
    stage5_cancel_rate AS (
        -- Stage 5: cancellation_rate = частка замовлень зі статусом 'canceled'
        SELECT
            customer_id,
            AVG(
                CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
            )::NUMERIC(6, 4) AS cancellation_rate
        FROM stage1_orders_total
        GROUP BY customer_id
    ),
    stage6_category_revenue AS (
        -- Stage 6: revenue per (customer, product category)
        SELECT
            o.customer_id,
            COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
            SUM(
                COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
            )::NUMERIC(12, 2) AS category_revenue
        FROM olist_orders AS o
        JOIN olist_order_items AS oi
            ON oi.order_id = o.order_id
        LEFT JOIN olist_products AS p
            ON p.product_id = oi.product_id
        GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
    ),
    stage7_preferred_category AS (
        -- Stage 7: preferred_category = top-1 категорія за revenue
        --          (детермінований tie-break за назвою)
        SELECT
            customer_id,
            product_category_name,
            category_revenue
        FROM (
            SELECT
                cr.*,
                ROW_NUMBER() OVER (
                    PARTITION BY cr.customer_id
                    ORDER BY cr.category_revenue DESC, cr.product_category_name
                ) AS rn
            FROM stage6_category_revenue AS cr
        ) AS ranked
        WHERE rn = 1
    )
    -- Final: customer-level feature row
    --        (LEFT JOIN -> клієнти без замовлень теж отримують рядок)
    SELECT
        c.customer_id,
        c.customer_state,
        COALESCE(coh.recency_days, 9999) AS recency_days,
        COALESCE(coh.frequency, 0) AS frequency,
        COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
        coh.first_order_date,
        coh.cohort_quarter,
        COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
        COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
        COALESCE(pc.product_category_name, '(none)') AS preferred_category,
        COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
    FROM olist_customers AS c
    LEFT JOIN stage3_cohort AS coh
        ON coh.customer_id = c.customer_id
    LEFT JOIN stage4_rolling_aov AS aov
        ON aov.customer_id = c.customer_id
       AND aov.rn_recent = 1
    LEFT JOIN stage5_cancel_rate AS cancel
        ON cancel.customer_id = c.customer_id
    LEFT JOIN stage7_preferred_category AS pc
        ON pc.customer_id = c.customer_id
)
SELECT
    COUNT(*)                               AS n_rows,
    COUNT(DISTINCT customer_id)            AS n_distinct_customers,
    (SELECT COUNT(*) FROM olist_customers) AS n_customers_source,
    MIN(recency_days)                      AS min_recency,
    MIN(cancellation_rate)                 AS min_cancel_rate,
    MAX(cancellation_rate)                 AS max_cancel_rate, -- у [0, 1]
    COUNT(*) FILTER (
        WHERE preferred_category = '(none)'
    )                                      AS n_no_category
FROM features;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[(99441, 99441, 99441, 1, Decimal('0.0000'), Decimal('1.0000'), 775)]

Olist **не має** referral-таблиці, тому `hw5_referrals` $-$ **синтетична навчальна** таблиця: перші 10 клієнтів (за `customer_id`) утворюють ланцюжок `c1` $\rightarrow$ `c2` $\rightarrow$ `…` $\rightarrow$ `c10`.

Constraints таблиці: `PRIMARY KEY (referred_customer_id)` $-$ кожного клієнта може запросити лише один referrer (граф = ліс дерев), `CHECK (referrer <> referred)` $-$ заборона self-loop, FK на `olist_customers`.

In [18]:
%%sql
DROP TABLE IF EXISTS hw5_referrals CASCADE;

CREATE TABLE hw5_referrals (
    referrer_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (referred_customer_id),
    CHECK (referrer_customer_id <> referred_customer_id)
);

-- Індекс на referrer: recursive part робить JOIN по referrer_customer_id
CREATE INDEX idx_hw5_referrals_referrer ON hw5_referrals (referrer_customer_id);

WITH ordered_customers AS (
    SELECT
        customer_id,
        ROW_NUMBER() OVER (ORDER BY customer_id) AS rn
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 10
)
INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    prev.customer_id AS referrer_customer_id,
    nxt.customer_id AS referred_customer_id
FROM ordered_customers AS prev
JOIN ordered_customers AS nxt
    ON nxt.rn = prev.rn + 1
ON CONFLICT (referred_customer_id) DO NOTHING;

SELECT
    referrer_customer_id,
    referred_customer_id
FROM hw5_referrals
ORDER BY referrer_customer_id, referred_customer_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
Done.
Done.
9 rows affected.
9 rows affected.

[('00012a2ce6f8dcda20d059ce98491703', '000161a058600d5901f007fab4c27140'),
 ('000161a058600d5901f007fab4c27140', '0001fd6190edaaf884bcaf3d49edf079'),
 ('0001fd6190edaaf884bcaf3d49edf079', '0002414f95344307404f0ace7a26f1d5'),
 ('0002414f95344307404f0ace7a26f1d5', '000379cdec625522490c315e70c7a9fb'),
 ('000379cdec625522490c315e70c7a9fb', '0004164d20a9e969af783496f3408652'),
 ('0004164d20a9e969af783496f3408652', '000419c5494106c306a97b5635748086'),
 ('000419c5494106c306a97b5635748086', '00046a560d407e99b969756e0b10f282'),
 ('00046a560d407e99b969756e0b10f282', '00050bf6e01e69d5c0fd612f1bcfb69c'),
 ('00050bf6e01e69d5c0fd612f1bcfb69c', '000598caf2ef4117407665ac33275130')]

### 3.1. Recursive CTE: depth + path з двома захистами від нескінченної рекурсії

* **Anchor** $-$ корені дерева: клієнти, яких ніхто не запросив. Anti-join через `NOT EXISTS` (NULL-safe; `NOT IN` повернув би 0 рядків, якби в підзапиті з’явився хоча б один `NULL`).
* **Recursive part** $-$ перехід referrer $\rightarrow$ referred.
* **Termination:**
  1. `NOT r.referred_customer_id = ANY(rd.path_ids)` $-$ не заходимо у вузол, який вже є в поточному шляху (cycle guard);
  2. `rd.depth < 50` $-$ жорстка межа глибини (depth guard).

In [19]:
%%sql
WITH RECURSIVE referral_depth AS (
    -- ANCHOR: root customers, які не були referred іншими customers (NULL-safe anti-join)
    SELECT
        c.customer_id,
        1 AS depth,
        ARRAY[c.customer_id]::TEXT[] AS path_ids,
        c.customer_id::TEXT AS path_text
    FROM olist_customers AS c
    WHERE NOT EXISTS (
        SELECT 1
        FROM hw5_referrals AS r
        WHERE r.referred_customer_id = c.customer_id
    )

    UNION ALL

    -- RECURSIVE: перейти від referrer до його referred customers
    SELECT
        r.referred_customer_id AS customer_id,
        rd.depth + 1 AS depth,
        rd.path_ids || r.referred_customer_id AS path_ids,
        rd.path_text || ' -> ' || r.referred_customer_id AS path_text
    FROM hw5_referrals AS r
    JOIN referral_depth AS rd
        ON rd.customer_id = r.referrer_customer_id
    WHERE NOT r.referred_customer_id = ANY(rd.path_ids)   -- cycle guard
      AND rd.depth < 50                                   -- depth guard
)
SELECT
    depth,
    COUNT(*) AS n_customers,
    MAX(path_text) AS sample_path
FROM referral_depth
GROUP BY depth
ORDER BY depth;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
10 rows affected.

[(1, 99432, 'ffffe8b65bbe3087b653a978c870db99'),
 (2, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140'),
 (3, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079'),
 (4, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5'),
 (5, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 000379cdec625522490c315e70c7a9fb'),
 (6, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 000379cdec625522490c315e70c7a9fb -> 0004164d20a9e969af783496f3408652'),
 (7, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 000379cdec625522490c315e70c7a9fb -> 0004164d20a9e969af783496f3408652 -> 000419c5494106c306a97b5635748086'),
 (8, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 000379cdec625522490c315e70c7a9fb -> 0004164d20a9e969af783496f3408652 -> 000419c5494106c306a97b5635748086 -> 00046a560d407e99b969756e0b10f282'),
 (9, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 00037 ... (22 characters truncated) ... 7a9fb -> 0004164d20a9e969af783496f3408652 -> 000419c5494106c306a97b5635748086 -> 00046a560d407e99b969756e0b10f282 -> 00050bf6e01e69d5c0fd612f1bcfb69c'),
 (10, 1, '00012a2ce6f8dcda20d059ce98491703 -> 000161a058600d5901f007fab4c27140 -> 0001fd6190edaaf884bcaf3d49edf079 -> 0002414f95344307404f0ace7a26f1d5 -> 00037 ... (58 characters truncated) ... 08652 -> 000419c5494106c306a97b5635748086 -> 00046a560d407e99b969756e0b10f282 -> 00050bf6e01e69d5c0fd612f1bcfb69c -> 000598caf2ef4117407665ac33275130')]

Інтерпретація:

> на depth = 1 $-$ усі клієнти-корені (усі, кого ніхто не запросив, включно з першим у ланцюжку); далі по одному клієнту на кожному рівні 2…10 $-$ це синтетичний ланцюжок із 9 ребер. Найдовший шлях має 10 вузлів.

### 3.2. Демонстрація: що відбувається з циклом A $\rightarrow$ B $\rightarrow$ A

У `hw5_referrals` цикл неможливий лише частково (PK забороняє двох referrer-ів, CHECK — self-loop), але цикл `A` $\rightarrow$ `B` $\rightarrow$ `A` формально **дозволений** схемою. Тому покажемо поведінку guard-ів на окремому тестовому графі `A` $\rightarrow$ `B` $\rightarrow$ `C` $\rightarrow$ `A`.

In [20]:
%%sql
-- Цикл A -> B -> C -> A. Стартуємо з A (anchor за NOT EXISTS тут дав би 0 рядків:
-- у чистому циклі КОЖЕН вузол є чиїмось referred, тож коренів немає).
WITH RECURSIVE
edges(referrer_customer_id, referred_customer_id) AS (
    VALUES
        ('A', 'B'),
        ('B', 'C'),
        ('C', 'A')
),
walk AS (
    SELECT
        'A'::TEXT AS customer_id,
        1 AS depth,
        ARRAY['A']::TEXT[] AS path_ids,
        'A'::TEXT AS path_text
    UNION ALL
    SELECT
        e.referred_customer_id,
        w.depth + 1,
        w.path_ids || e.referred_customer_id,
        w.path_text || ' -> ' || e.referred_customer_id
    FROM edges AS e
    JOIN walk AS w
        ON w.customer_id = e.referrer_customer_id
    WHERE NOT e.referred_customer_id = ANY(w.path_ids)   -- C -> A відсікається: A вже в path
      AND w.depth < 50
)
SELECT *
FROM walk
ORDER BY depth;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
3 rows affected.

[('A', 1, ['A'], 'A'),
 ('B', 2, ['A', 'B'], 'A -> B'),
 ('C', 3, ['A', 'B', 'C'], 'A -> B -> C')]

In [22]:
%%sql
-- Альтернатива для PostgreSQL 14+: стандартний CYCLE-clause.
-- PostgreSQL сам веде шлях і позначає рядок, що замикає цикл (is_cycle = true),
-- не розгортаючи його далі.
WITH RECURSIVE
edges(referrer_customer_id, referred_customer_id) AS (
    VALUES
        ('A', 'B'),
        ('B', 'C'),
        ('C', 'A')
),
walk AS (
    SELECT
        'A'::TEXT AS customer_id,
        1 AS depth
    UNION ALL
    SELECT
        e.referred_customer_id,
        w.depth + 1
    FROM edges AS e
    JOIN walk AS w
        ON w.customer_id = e.referrer_customer_id
) CYCLE customer_id SET is_cycle USING cycle_path
SELECT
    customer_id,
    depth,
    is_cycle,
    cycle_path::TEXT AS cycle_path
FROM walk
ORDER BY depth;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
4 rows affected.

[('A', 1, False, '{(A)}'),
 ('B', 2, False, '{(A),(B)}'),
 ('C', 3, False, '{(A),(B),(C)}'),
 ('A', 4, True, '{(A),(B),(C),(A)}')]

Без guard-а запит з `UNION ALL` на графі `A` $\rightarrow$ `B` $\rightarrow$ `C` $\rightarrow$ `A` генерував би рядки нескінченно (A, B, C, A, B, …) до вичерпання пам’яті/`statement_timeout`. З path-guard рекурсія зупиняється після C (3 рядки); CYCLE-clause видає ще один рядок `A` з `is_cycle = true` і далі його не розгортає.

## 4. Materialized View з CONCURRENT REFRESH

MV містить **повний** результат pipeline з Завдання 2 (усі 8 stages, той самий набір колонок), без `ORDER BY/LIMIT` $-$ один рядок на кожного клієнта.

In [23]:
%%sql
DROP MATERIALIZED VIEW IF EXISTS mv_olist_customer_features CASCADE;

CREATE MATERIALIZED VIEW mv_olist_customer_features AS
WITH
reference_date AS (
    -- Stage 0: стабільна reference date, обчислена з самого датасету
    -- (MAX дата покупки + 1 день) -> результат не змінюється з плином часу
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: order-level grain: замовлення + order_total (price + freight) + статус
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM per customer: recency_days (від reference_date), frequency, monetary
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort_quarter = квартал першого замовлення
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day AVG(order_total) per customer (window RANGE 30 days);
    --          rn_recent = 1 позначає останнє замовлення -> актуальне значення ознаки
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation_rate = частка замовлень зі статусом 'canceled'
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue per (customer, product category)
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred_category = top-1 категорія за revenue
    --          (детермінований tie-break за назвою)
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
-- Final: customer-level feature row (LEFT JOIN -> клієнти без замовлень теж отримують рядок)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id;

-- UNIQUE (не partial) індекс на customer_id: обов'язкова умова для REFRESH ... CONCURRENTLY
CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id
    ON mv_olist_customer_features (customer_id);

ANALYZE mv_olist_customer_features;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
99441 rows affected.
Done.
Done.

[]

In [24]:
%%sql
SELECT COUNT(*) AS n_rows
FROM mv_olist_customer_features;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[(99441,)]

In [25]:
%%sql
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST, customer_id
LIMIT 5;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
5 rows affected.

[('1617b1357756262bfa56ab541c47bc16', 'RJ', 384, 1, Decimal('13664.08'), datetime.date(2017, 9, 29), datetime.date(2017, 7, 1), Decimal('13664.08'), Decimal('0.0000'), 'telefonia_fixa', Decimal('13664.08')),
 ('ec5b2ba62e574342386871631fafd3fc', 'ES', 95, 1, Decimal('7274.88'), datetime.date(2018, 7, 15), datetime.date(2018, 7, 1), Decimal('7274.88'), Decimal('0.0000'), 'telefonia_fixa', Decimal('7274.88')),
 ('c6e2731c5b391845f6800c97401a43a9', 'MS', 613, 1, Decimal('6929.31'), datetime.date(2017, 2, 12), datetime.date(2017, 1, 1), Decimal('6929.31'), Decimal('0.0000'), 'utilidades_domesticas', Decimal('6929.31')),
 ('f48d464a0baaea338cb25f816991ab1f', 'ES', 85, 1, Decimal('6922.21'), datetime.date(2018, 7, 25), datetime.date(2018, 7, 1), Decimal('6922.21'), Decimal('0.0000'), 'pcs', Decimal('6922.21')),
 ('3fd6777bbce08a352fddd04e4a7cc8f6', 'SP', 512, 1, Decimal('6726.66'), datetime.date(2017, 5, 24), datetime.date(2017, 4, 1), Decimal('6726.66'), Decimal('0.0000'), 'artes', Decimal('6726.66'))]

In [26]:
%%sql
-- Перевірка, що для MV існує саме UNIQUE-індекс
SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename = 'mv_olist_customer_features';

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[('idx_mv_olist_customer_features_customer_id', 'CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id ON public.mv_olist_customer_features USING btree (customer_id)')]

Concurrent refresh (окрема клітинка, після створення `UNIQUE INDEX`). `CONCURRENTLY` будує нову версію даних поруч і застосовує diff, тому читачі MV не блокуються під час оновлення.

In [27]:
%%sql
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.

[]

In [28]:
%%sql
-- Після refresh: кількість рядків збігається з кількістю клієнтів, дублікатів немає
SELECT
    (
        SELECT COUNT(*)
        FROM mv_olist_customer_features
    ) AS mv_rows,
    (
        SELECT COUNT(DISTINCT customer_id)
        FROM mv_olist_customer_features
    ) AS mv_distinct_customers,
    (
        SELECT COUNT(*)
        FROM olist_customers
    ) AS source_customers;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
1 rows affected.

[(99441, 99441, 99441)]

## 5. EXPLAIN (ANALYZE, BUFFERS)

### 5.1. Повне переобчислення CTE-pipeline (RFM-частина, шаблон завдання)

In [29]:
%%sql
EXPLAIN (ANALYZE, BUFFERS)
WITH
reference_date AS (
    SELECT
        (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
)
SELECT *
FROM stage2_rfm
ORDER BY monetary DESC NULLS LAST
LIMIT 10;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
32 rows affected.

[('Limit  (cost=33611.31..33611.33 rows=10 width=65) (actual time=1523.999..1524.009 rows=10 loops=1)',),
 ('  Buffers: shared hit=105261, temp read=961 written=1696',),
 ('  ->  Sort  (cost=33611.31..33611.81 rows=200 width=65) (actual time=1523.996..1524.005 rows=10 loops=1)',),
 ('        Sort Key: stage2_rfm.monetary DESC NULLS LAST',),
 ('        Sort Method: top-N heapsort  Memory: 27kB',),
 ('        Buffers: shared hit=105261, temp read=961 written=1696',),
 ('        ->  Subquery Scan on stage2_rfm  (cost=33601.49..33606.99 rows=200 width=65) (actual time=1339.437..1493.466 rows=99441 loops=1)',),
 ('              Buffers: shared hit=105261, temp read=961 written=1696',),
 ('              ->  HashAggregate  (cost=33601.49..33604.99 rows=200 width=69) (actual time=1339.435..1481.443 rows=99441 loops=1)',),
 ('                    Group Key: o.customer_id, (((max(olist_orders.order_purchase_timestamp))::date + 1))',),
 ('                    Batches: 21  Memory Usage: 8265kB  Disk Usage: 7400kB',),
 ('                    Buffers: shared hit=105261, temp read=961 written=1696',),
 ('                    ->  Nested Loop  (cost=3051.85..32109.87 rows=99441 width=57) (actual time=33.133..1125.695 rows=99441 loops=1)',),
 ('                          Buffers: shared hit=105261',),
 ('                          ->  Aggregate  (cost=3051.01..3051.03 rows=1 width=4) (actual time=33.032..33.033 rows=1 loops=1)',),
 ('                                Buffers: shared hit=1808',),
 ('                                ->  Seq Scan on olist_orders  (cost=0.00..2802.41 rows=99441 width=8) (actual time=0.011..13.577 rows=99441 loops=1)',),
 ('                                      Buffers: shared hit=1808',),
 ('                          ->  GroupAggregate  (cost=0.83..27070.03 rows=99441 width=103) (actual time=0.091..1055.781 rows=99441 loops=1)',),
 ('                                Group Key: o.order_id',),
 ('                                Buffers: shared hit=103453',),
 ('                                ->  Merge Left Join  (cost=0.83..24484.93 rows=112650 width=95) (actual time=0.060..709.917 rows=113425 loops=1)',),
 ('                                      Merge Cond: (o.order_id = oi.order_id)',),
 ('                                      Buffers: shared hit=103453',),
 ('                                      ->  Index Scan using olist_orders_pkey on olist_orders o  (cost=0.42..12563.91 rows=99441 width=83) (actual time=0.031..322.121 rows=99441 loops=1)',),
 ('                                            Buffers: shared hit=100347',),
 ('                                      ->  Index Scan using olist_order_items_pkey on olist_order_items oi  (cost=0.42..10264.29 rows=112650 width=45) (actual time=0.019..96.198 rows=112650 loops=1)',),
 ('                                            Buffers: shared hit=3106',),
 ('Planning:',),
 ('  Buffers: shared hit=18',),
 ('Planning Time: 0.863 ms',),
 ('Execution Time: 1525.686 ms',)]

### 5.2. Повний 8-stage pipeline (той самий запит, що й у MV) $-$ щоб знайти найдорожчий feature

In [30]:
%%sql
EXPLAIN (ANALYZE, BUFFERS)
WITH
reference_date AS (
    -- Stage 0: стабільна reference date, обчислена з самого датасету
    -- (MAX дата покупки + 1 день) -> результат не змінюється з плином часу
    SELECT
        (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: order-level grain: замовлення + order_total (price + freight) + статус
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM per customer: recency_days (від reference_date), frequency, monetary
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort_quarter = квартал першого замовлення
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day AVG(order_total) per customer (window RANGE 30 days);
    --          rn_recent = 1 позначає останнє замовлення -> актуальне значення ознаки
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation_rate = частка замовлень зі статусом 'canceled'
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue per (customer, product category)
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred_category = top-1 категорія за revenue
    --          (детермінований tie-break за назвою)
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
-- Final: customer-level feature row (LEFT JOIN -> клієнти без замовлень теж отримують рядок)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id
ORDER BY monetary DESC NULLS LAST, c.customer_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
135 rows affected.

[('Sort  (cost=129440.00..129688.61 rows=99441 width=150) (actual time=3575.109..3619.331 rows=99441 loops=1)',),
 ("  Sort Key: ((COALESCE(r.monetary, '0'::numeric))::numeric(12,2)) DESC NULLS LAST, c.customer_id",),
 ('  Sort Method: external merge  Disk: 10376kB',),
 ('  Buffers: shared hit=111708, temp read=9692 written=9844',),
 ('  CTE stage1_orders_total',),
 ('    ->  GroupAggregate  (cost=0.83..27070.03 rows=99441 width=103) (actual time=0.146..444.121 rows=99441 loops=1)',),
 ('          Group Key: o_1.order_id',),
 ('          Buffers: shared hit=103453',),
 ('          ->  Merge Left Join  (cost=0.83..24484.93 rows=112650 width=95) (actual time=0.103..299.939 rows=113425 loops=1)',),
 ('                Merge Cond: (o_1.order_id = oi_1.order_id)',),
 ('                Buffers: shared hit=103453',),
 ('                ->  Index Scan using olist_orders_pkey on olist_orders o_1  (cost=0.42..12563.91 rows=99441 width=83) (actual time=0.037..118.678 rows=99441 loops=1)',),
 ('                      Buffers: shared hit=100347',),
 ('                ->  Index Scan using olist_order_items_pkey on olist_order_items oi_1  (cost=0.42..10264.29 rows=112650 width=45) (actual time=0.030..59.369 rows=112650 loops=1)',),
 ('                      Buffers: shared hit=3106',),
 ('  ->  Hash Left Join  (cost=59301.67..86636.10 rows=99441 width=150) (actual time=2678.710..3427.363 rows=99441 loops=1)',),
 ('        Hash Cond: (c.customer_id = cancel.customer_id)',),
 ('        Buffers: shared hit=111708, temp read=8395 written=8544',),
 ('        ->  Hash Left Join  (cost=56559.54..81892.72 rows=99441 width=132) (actual time=2406.845..3009.063 rows=99441 loops=1)',),
 ('              Hash Cond: (c.customer_id = r.customer_id)',),
 ('              Buffers: shared hit=111708, temp read=6299 written=7039',),
 ('              ->  Hash Right Join  (cost=49025.67..71622.22 rows=99441 width=100) (actual time=2060.300..2551.202 rows=99441 loops=1)',),
 ('                    Hash Cond: (ranked.customer_id = c.customer_id)',),
 ('                    Buffers: shared hit=109900, temp read=3010 written=4337',),
 ('                    ->  Subquery Scan on ranked  (cost=16948.65..38549.46 rows=563 width=81) (actual time=515.091..894.772 rows=98666 loops=1)',),
 ('                          Filter: (ranked.rn = 1)',),
 ('                          Buffers: shared hit=4997, temp read=996 written=998',),
 ('                          ->  WindowAgg  (cost=16948.65..37141.34 rows=112650 width=89) (actual time=515.079..878.928 rows=98666 loops=1)',),
 ('                                Run Condition: (row_number() OVER (?) <= 1)',),
 ('                                Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                ->  Incremental Sort  (cost=16948.65..34888.34 rows=112650 width=81) (actual time=515.052..808.166 rows=99470 loops=1)',),
 ("                                      Sort Key: o.customer_id, ((sum((COALESCE(oi.price, '0'::numeric) + COALESCE(oi.freight_value, '0'::numeric))))::numeric(12,2)) DESC, (COALESCE(p.product_category_name, '(unknown)'::text))",),
 ('                                      Presorted Key: o.customer_id',),
 ('                                      Full-sort Groups: 3108  Sort Method: quicksort  Average Memory: 27kB  Peak Memory: 27kB',),
 ('                                      Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                      ->  Finalize GroupAggregate  (cost=16865.60..28329.44 rows=112650 width=81) (actual time=514.860..751.977 rows=99470 loops=1)',),
 ("                                            Group Key: o.customer_id, (COALESCE(p.product_category_name, '(unknown)'::text))",),
 ('                                            Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                            ->  Gather Merge  (cost=16865.60..25977.04 rows=66265 width=97) (actual time=514.795..642.915 rows=99672 loops=1)',),
 ('                                                  Workers Planned: 1',),
 ('                                                  Workers Launched: 1',),
 ('                                                  Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                                  ->  Partial GroupAggregate  (cost=15865.59..17522.22 rows=66265 width=97) (actual time=474.422..579.663 rows=49836 loops=2)',),
 ("                                                        Group Key: o.customer_id, (COALESCE(p.product_category_name, '(unknown)'::text))",),
 ('                                                        Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                                        ->  Sort  (cost=15865.59..16031.25 rows=66265 width=77) (actual time=474.340..503.518 rows=56325 loops=2)',),
 ("                                                              Sort Key: o.customer_id, (COALESCE(p.product_category_name, '(unknown)'::text))",),
 ('                                                              Sort Method: external merge  Disk: 3512kB',),
 ('                                                              Buffers: shared hit=4997, temp read=996 written=998',),
 ('                                                              Worker 0:  Sort Method: external merge  Disk: 4456kB',),
 ('                                                              ->  Hash Left Join  (cost=4302.53..7612.10 rows=66265 width=77) (actual time=104.259..222.674 rows=56325 loops=2)',),
 ('                                                                    Hash Cond: (oi.product_id = p.product_id)',),
 ('                                                                    Buffers: shared hit=4992',),
 ('                                                                    ->  Parallel Hash Join  (cost=3124.13..6259.74 rows=66265 width=78) (actual time=82.102..156.524 rows=56325 loops=2)',),
 ('                                                                          Hash Cond: (oi.order_id = o.order_id)',),
 ('                                                                          Buffers: shared hit=4118',),
 ('                                                                          ->  Parallel Seq Scan on olist_order_items oi  (cost=0.00..2961.65 rows=66265 width=78) (actual time=0.014..8.932 rows=56325 loops=2)',),
 ('                                                                                Buffers: shared hit=2299',),
 ('                                                                          ->  Parallel Hash  (cost=2392.95..2392.95 rows=58495 width=66) (actual time=79.412..79.414 rows=49720 loops=2)',),
 ('                                                                                Buckets: 131072  Batches: 1  Memory Usage: 11200kB',),
 ('                                                                                Buffers: shared hit=1808',),
 ('                                                                                ->  Parallel Seq Scan on olist_orders o  (cost=0.00..2392.95 rows=58495 width=66) (actual time=18.539..34.369 rows=49720 loops=2)',),
 ('                                                                                      Buffers: shared hit=1808',),
 ('                                                                    ->  Hash  (cost=766.51..766.51 rows=32951 width=48) (actual time=21.691..21.692 rows=32951 loops=2)',),
 ('                                                                          Buckets: 65536  Batches: 1  Memory Usage: 3108kB',),
 ('                                                                          Buffers: shared hit=874',),
 ('                                                                          ->  Seq Scan on olist_products p  (cost=0.00..766.51 rows=32951 width=48) (actual time=0.048..7.965 rows=32951 loops=2)',),
 ('                                                                                Buffers: shared hit=874',),
 ('                    ->  Hash  (cost=29862.00..29862.00 rows=99441 width=52) (actual time=1544.836..1544.846 rows=99441 loops=1)',),
 ('                          Buckets: 131072  Batches: 2  Memory Usage: 4681kB',),
 ('                          Buffers: shared hit=104903, temp read=1181 written=2885',),
 ('                          ->  Hash Right Join  (cost=18724.07..29862.00 rows=99441 width=52) (actual time=1069.213..1492.635 rows=99441 loops=1)',),
 ('                                Hash Cond: (aov.customer_id = c.customer_id)',),
 ('                                Buffers: shared hit=104903, temp read=1181 written=2506',),
 ('                                ->  Subquery Scan on aov  (cost=15036.65..26173.27 rows=497 width=48) (actual time=792.696..1140.002 rows=99441 loops=1)',),
 ('                                      Filter: (aov.rn_recent = 1)',),
 ('                                      Buffers: shared hit=103453, temp read=1181 written=2506',),
 ('                                      ->  WindowAgg  (cost=15036.65..24930.26 rows=99441 width=112) (actual time=792.691..1128.051 rows=99441 loops=1)',),
 ('                                            Filter: ((row_number() OVER (?)) <= 1)',),
 ('                                            Buffers: shared hit=103453, temp read=1181 written=2506',),
 ('                                            ->  Incremental Sort  (cost=15036.65..22941.44 rows=99441 width=96) (actual time=791.992..958.010 rows=99441 loops=1)',),
 ('                                                  Sort Key: s.customer_id, s.order_ts',),
 ('                                                  Presorted Key: s.customer_id',),
 ('                                                  Full-sort Groups: 3108  Sort Method: quicksort  Average Memory: 28kB  Peak Memory: 28kB',),
 ('                                                  Buffers: shared hit=103453, temp read=1181 written=2506',),
 ('                                                  ->  WindowAgg  (cost=15003.20..17240.62 rows=99441 width=96) (actual time=791.878..913.998 rows=99441 loops=1)',),
 ('                                                        Run Condition: (row_number() OVER (?) <= 1)',),
 ('                                                        Buffers: shared hit=103453, temp read=1181 written=2506',),
 ('                                                        ->  Sort  (cost=15003.20..15251.80 rows=99441 width=88) (actual time=791.812..856.122 rows=99441 loops=1)',),
 ('                                                              Sort Key: s.customer_id, s.order_ts DESC, s.order_id DESC',),
 ('                                                              Sort Method: external merge  Disk: 9448kB',),
 ('                                                              Buffers: shared hit=103453, temp read=1181 written=2506',),
 ('                                                              ->  CTE Scan on stage1_orders_total s  (cost=0.00..1988.82 rows=99441 width=88) (actual time=0.156..548.477 rows=99441 loops=1)',),
 ('                                                                    Buffers: shared hit=103453, temp written=1322',),
 ('                                ->  Hash  (cost=2444.41..2444.41 rows=99441 width=36) (actual time=276.140..276.142 rows=99441 loops=1)',),
 ('                                      Buckets: 131072  Batches: 1  Memory Usage: 7628kB',),
 ('                                      Buffers: shared hit=1450',),
 ('                                      ->  Seq Scan on olist_customers c  (cost=0.00..2444.41 rows=99441 width=36) (actual time=157.046..211.062 rows=99441 loops=1)',),
 ('                                            Buffers: shared hit=1450',),
 ('              ->  Hash  (cost=7531.37..7531.37 rows=200 width=64) (actual time=346.416..346.422 rows=99441 loops=1)',),
 ('                    Buckets: 131072 (originally 1024)  Batches: 2 (originally 1)  Memory Usage: 7169kB',),
 ('                    Buffers: shared hit=1808, temp read=2284 written=2185',),
 ('                    ->  Subquery Scan on r  (cost=7525.87..7531.37 rows=200 width=64) (actual time=142.554..297.031 rows=99441 loops=1)',),
 ('                          Buffers: shared hit=1808, temp read=2284 written=1697',),
 ('                          ->  HashAggregate  (cost=7525.87..7529.37 rows=200 width=68) (actual time=142.535..282.722 rows=99441 loops=1)',),
 ('                                Group Key: s_1.customer_id, (((max(olist_orders.order_purchase_timestamp))::date + 1))',),
 ('                                Batches: 21  Memory Usage: 8265kB  Disk Usage: 7400kB',),
 ('                                Buffers: shared hit=1808, temp read=2284 written=1697',),
 ('                                ->  Nested Loop  (cost=3051.01..6034.26 rows=99441 width=56) (actual time=19.393..50.996 rows=99441 loops=1)',),
 ('                                      Buffers: shared hit=1808, temp read=1323 written=1',),
 ('                                      ->  Aggregate  (cost=3051.01..3051.03 rows=1 width=4) (actual time=19.249..19.251 rows=1 loops=1)',),
 ('                                            Buffers: shared hit=1808',),
 ('                                            ->  Seq Scan on olist_orders  (cost=0.00..2802.41 rows=99441 width=8) (actual time=0.018..8.196 rows=99441 loops=1)',),
 ('                                                  Buffers: shared hit=1808',),
 ('                                      ->  CTE Scan on stage1_orders_total s_1  (cost=0.00..1988.82 rows=99441 width=52) (actual time=0.127..16.024 rows=99441 loops=1)',),
 ('                                            Buffers: temp read=1323 written=1',),
 ('        ->  Hash  (cost=2739.63..2739.63 rows=200 width=46) (actual time=271.737..271.740 rows=99441 loops=1)',),
 ('              Buckets: 131072 (originally 1024)  Batches: 1 (originally 1)  Memory Usage: 7629kB',),
 ('              Buffers: temp read=2096 written=1505',),
 ('              ->  Subquery Scan on cancel  (cost=2734.63..2739.63 rows=200 width=46) (actual time=95.361..240.735 rows=99441 loops=1)',),
 ('                    Buffers: temp read=2096 written=1505',),
 ('                    ->  HashAggregate  (cost=2734.63..2737.63 rows=200 width=46) (actual time=95.353..227.822 rows=99441 loops=1)',),
 ('                          Group Key: stage1_orders_total.customer_id',),
 ('                          Batches: 21  Memory Usage: 8265kB  Disk Usage: 7200kB',),
 ('                          Buffers: temp read=2096 written=1505',),
 ('                          ->  CTE Scan on stage1_orders_total  (cost=0.00..1988.82 rows=99441 width=64) (actual time=0.016..15.343 rows=99441 loops=1)',),
 ('                                Buffers: temp read=1323',),
 ('Planning:',),
 ('  Buffers: shared hit=42',),
 ('Planning Time: 8.486 ms',),
 ('JIT:',),
 ('  Functions: 144',),
 ('  Options: Inlining false, Optimization false, Expressions true, Deforming true',),
 ('  Timing: Generation 20.765 ms, Inlining 0.000 ms, Optimization 7.758 ms, Emission 205.570 ms, Total 234.092 ms',),
 ('Execution Time: 3650.304 ms',)]

### 5.3. Lookup з MV за `customer_id` (має використовувати UNIQUE INDEX)

In [31]:
%%sql
EXPLAIN (ANALYZE, BUFFERS)
WITH target_customer AS (
    SELECT customer_id
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 1
)
SELECT mv.*
FROM mv_olist_customer_features AS mv
JOIN target_customer AS t
    ON t.customer_id = mv.customer_id;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
14 rows affected.

[('Nested Loop  (cost=0.83..8.91 rows=1 width=92) (actual time=0.083..0.084 rows=1 loops=1)',),
 ('  Buffers: shared hit=8',),
 ('  ->  Limit  (cost=0.42..0.47 rows=1 width=33) (actual time=0.058..0.059 rows=1 loops=1)',),
 ('        Buffers: shared hit=4',),
 ('        ->  Index Only Scan using olist_customers_pkey on olist_customers  (cost=0.42..5328.03 rows=99441 width=33) (actual time=0.057..0.057 rows=1 loops=1)',),
 ('              Heap Fetches: 0',),
 ('              Buffers: shared hit=4',),
 ('  ->  Index Scan using idx_mv_olist_customer_features_customer_id on mv_olist_customer_features mv  (cost=0.42..8.44 rows=1 width=92) (actual time=0.019..0.019 rows=1 loops=1)',),
 ('        Index Cond: (customer_id = olist_customers.customer_id)',),
 ('        Buffers: shared hit=4',),
 ('Planning:',),
 ('  Buffers: shared hit=7 read=1',),
 ('Planning Time: 1.469 ms',),
 ('Execution Time: 0.130 ms',)]

### 5.4. Top-N з MV з окремим індексом на `monetary`

In [32]:
%%sql
-- Індекс збігається з порядком запиту (DESC NULLS FIRST за замовчуванням для DESC;
-- monetary NOT NULL завдяки COALESCE, тож NULLS LAST не заважає),
-- щоб спрацював Index Scan без Sort
CREATE INDEX IF NOT EXISTS idx_mv_olist_customer_features_monetary
    ON mv_olist_customer_features (monetary DESC NULLS LAST);

EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM mv_olist_customer_features
ORDER BY monetary DESC NULLS LAST
LIMIT 10;

 * postgresql+psycopg2://postgres:***@localhost:5432/postgres
Done.
8 rows affected.

[('Limit  (cost=0.42..1.32 rows=10 width=92) (actual time=0.088..0.105 rows=10 loops=1)',),
 ('  Buffers: shared hit=10 read=3',),
 ('  ->  Index Scan using idx_mv_olist_customer_features_monetary on mv_olist_customer_features  (cost=0.42..8995.72 rows=99441 width=92) (actual time=0.087..0.102 rows=10 loops=1)',),
 ('        Buffers: shared hit=10 read=3',),
 ('Planning:',),
 ('  Buffers: shared hit=15 read=1',),
 ('Planning Time: 0.371 ms',),
 ('Execution Time: 0.131 ms',)]

### 5.5. Зведене порівняння часу виконання (з тих самих `EXPLAIN ANALYZE`, формат JSON)

In [34]:
FULL_PIPELINE_SQL = r'''
WITH
reference_date AS (
    -- Stage 0: стабільна reference date, обчислена з самого датасету
    -- (MAX дата покупки + 1 день) -> результат не змінюється з плином часу
    SELECT
        (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: order-level grain: замовлення + order_total (price + freight) + статус
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM per customer: recency_days (від reference_date), frequency, monetary
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort_quarter = квартал першого замовлення
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day AVG(order_total) per customer (window RANGE 30 days);
    --          rn_recent = 1 позначає останнє замовлення -> актуальне значення ознаки
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation_rate = частка замовлень зі статусом 'canceled'
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue per (customer, product category)
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred_category = top-1 категорія за revenue
    --          (детермінований tie-break за назвою)
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
-- Final: customer-level feature row (LEFT JOIN -> клієнти без замовлень теж отримують рядок)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id
ORDER BY monetary DESC NULLS LAST, c.customer_id
LIMIT 30
'''

scenarios = {
    'full 8-stage pipeline (recompute)': FULL_PIPELINE_SQL,
    'MV lookup by customer_id': '''
        WITH target_customer AS (SELECT customer_id FROM olist_customers ORDER BY customer_id LIMIT 1)
        SELECT mv.* FROM mv_olist_customer_features AS mv
        JOIN target_customer AS t ON t.customer_id = mv.customer_id''',
    'MV top-10 by monetary': '''
        SELECT * FROM mv_olist_customer_features ORDER BY monetary DESC NULLS LAST LIMIT 10''',
    'REFRESH cost ~ full pipeline w/o LIMIT': FULL_PIPELINE_SQL.replace('LIMIT 20', ''),
}


def collect_nodes(node, acc):
    acc.append((node['Node Type'], node.get('Actual Total Time', 0.0)))
    for child in node.get('Plans', []):
        collect_nodes(child, acc)
    return acc


summary = []
with engine.connect() as conn:
    for name, q in scenarios.items():
        plan = conn.execute(text(
            'EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ' + q
        )).scalar()[0]
        nodes = collect_nodes(plan['Plan'], [])
        top = plan['Plan']
        summary.append({
            'scenario': name,
            'execution_ms': round(plan['Execution Time'], 3),
            'planning_ms': round(plan['Planning Time'], 3),
            'shared_buffers_hit+read':
                top.get('Shared Hit Blocks', 0) + top.get('Shared Read Blocks', 0),
            'node_types': ', '.join(sorted({n for n, _ in nodes})),
        })
summary_df = pd.DataFrame(summary)
pd.set_option('display.max_colwidth', 200)
display(summary_df)
full_ms = summary_df.loc[0, 'execution_ms']
lookup_ms = summary_df.loc[1, 'execution_ms']
print(
    '\n'
    'Lookup з MV швидший за повне переобчислення приблизно у'
    f'{full_ms / max(lookup_ms, 1e-3):,.0f} разів'
)

,scenario,execution_ms,planning_ms,shared_buffers_hit+read,node_types
0,full 8-stage pipeline (recompute),4784.084,3.055,111708,"Aggregate, CTE Scan, Gather Merge, Hash, Hash Join, Incremental Sort, Index Scan, Limit, Merge Join, Nested Loop, Seq Scan, Sort, Subquery Scan, WindowAgg"
1,MV lookup by customer_id,0.088,0.431,8,"Index Only Scan, Index Scan, Limit, Nested Loop"
2,MV top-10 by monetary,0.073,0.095,13,"Index Scan, Limit"
3,REFRESH cost ~ full pipeline w/o LIMIT,3291.194,2.203,111708,"Aggregate, CTE Scan, Gather Merge, Hash, Hash Join, Incremental Sort, Index Scan, Limit, Merge Join, Nested Loop, Seq Scan, Sort, Subquery Scan, WindowAgg"

Lookup з MV швидший за повне переобчислення приблизно у54,365 разів

# 6. Reflection

> Усі цифри взято з `EXPLAIN (ANALYZE, BUFFERS)` цього прогону: Colab, PostgreSQL 16.15, Olist (99 441 клієнт, 112 650 позицій), `work_mem` = 4 MB. Час між прогонами коливається: у 5.5 рядки 0 і 3 $-$ це той самий запит (`LIMIT 30` не прибирається через `replace('LIMIT 20', '')`), і він дав 4 784 та 3 291 ms. Тому стабільніший показник $-$ кількість buffers.

**1. Найдорожчий feature.**
> Повний pipeline (5.2, без `LIMIT`, тобто сам запит MV) виконується **3 650 ms**: `shared hit=111 708`, `temp read=9 692 / written=9 844`, з них JIT $-$ 234 ms. Базовий `stage1_orders_total` (`Merge Left Join` + `GroupAggregate`) коштує 444 ms і 103 453 buffers. Він використовується тричі, тому матеріалізується (`CTE Scan`).
> * Найдорожчий feature $-$ **`preferred_category`, $\approx$ 895 ms**: власний `Parallel Hash Join` orders×items, `Hash Left Join` products, `Sort … external merge` (3.5 + 4.5 MB), `Partial/Finalize GroupAggregate`, `Incremental Sort`, `WindowAgg`.
> * Другий $-$ **`avg_order_value_30d`, $\approx$590 ms** понад stage1: `Sort` за `(customer_id, order_ts DESC)` з `external merge Disk: 9448kB` + два `WindowAgg`.
> * RFM і `cancellation_rate` $-$ `HashAggregate` з `Batches: 21, Disk Usage ≈7.2–7.4 MB` ($\approx$300 і $\approx$270 ms). Фінальний `Sort` $-$ ще `external merge 10 376 kB`.
>
> Отже, вартість визначають **Sort / HashAggregate зі spill на диск і window functions**, а не JOIN-и: `Parallel Hash Join` займає лише $\approx$157 ms.

**2. Чи кешувати через MV?**
> Так. Lookup у MV (5.3) робить `Index Scan using idx_mv_…_customer_id`: **0.130 ms, 8 buffers**. Top-10 (5.4) робить `Index Scan using idx_mv_…_monetary` без `Sort`: 0.131 ms, 13 buffers. Порівняно з 3 650 ms і 111 708 buffers це в ~28 000 разів швидше і в ~14 000 разів менше buffers. Refresh коштує стільки ж, скільки 5.2 ($\approx$3.5 s), тому я обрав би **щодобовий** `REFRESH … CONCURRENTLY` після нічного ETL. Для статичного Olist достатньо on-demand після імпорту. Щогодинний refresh має сенс лише для online-скорингу.

**3. Коли VIEW кращий.**
> Коли потрібні свіжі дані на дешевому запиті: ad-hoc або debug одного клієнта, ознаки, що швидко змінюються (наприклад, статус останнього замовлення), або малий обсяг даних (stub-схема), де перерахунок дешевший за підтримку refresh.

**4. Termination recursive CTE.**
> Рекурсія зупиняється, коли recursive part повертає 0 рядків. Це гарантують дві умови: `NOT next_id = ANY(path_ids)` і `depth < 50`. Без них цикл `A` $\rightarrow$ `B` $\rightarrow$ `A` з `UNION ALL` розгортався б нескінченно. У демо 3.2 path-guard відсік ребро назад до A (3 рядки), а `CYCLE`-clause позначив його `is_cycle = true`. Чистий цикл не має кореня для anchor з `NOT EXISTS`, тому його треба виявляти окремо.

**5. Ключовий trade-off.**
> **Recompute-cost vs freshness.** Ми приймаємо застарілість до 24 год, щоб $\approx$3.5 s сортувань зі spill на диск виконувались раз на добу, а не при кожному читанні. Storage-cost (99 441 вузький рядок + 2 індекси) незначний, а latency читання вже забезпечують індекси.